// Creates a CV from scratch in the browser and checks that edits reach the PDF: node scripts/flow.mjs <out dir>
import { chromium } from 'playwright'
const out = process.argv[2]
const b = await chromium.launch(process.env.CHROMIUM_PATH ? { executablePath: process.env.CHROMIUM_PATH } : {})
const p = await b.newPage({ viewport: { width: 1360, height: 900 } })
const errors = []
p.on('pageerror', (e) => errors.push(e.message))
await p.goto('http://localhost:4173/')
await p.getByLabel('Sector').selectOption('healthcare')
await p.getByLabel('Applying in').selectOption('dach')
await p.getByRole('button', { name: /Create CV with/ }).click()
await p.waitForSelector('.preview-stack canvas', { timeout: 20000 })
await p.getByLabel('Full name').fill('Jonas Weber')
await p.getByLabel('Headline').fill('Facharzt für Innere Medizin')
await p.getByLabel('Date of birth').fill('14.03.1988')
await p.getByLabel('Nationality').fill('Deutsch')
await p.locator('section.card', { hasText: 'Grade, specialty, hospital' }).getByRole('button', { name: 'Add entry' }).click()
await p.getByLabel('Job title').first().fill('Assistenzarzt, Kardiologie')
await p.getByLabel('Employer').first().fill('Charité Universitätsmedizin')
await p.getByLabel('Achievements').first().fill('Betreuung von 24 Betten auf der kardiologischen Station\nÜber 300 Echokardiographien durchgeführt')
await p.getByRole('textbox', { name: 'Place' }).fill('Berlin')
await p.waitForTimeout(2000)
await p.screenshot({ path: `${out}/flow.png` })
const [pdf] = await Promise.all([p.waitForEvent('download'), p.getByRole('button', { name: 'PDF' }).click()])
await pdf.saveAs(`${out}/flow.pdf`)
const [docx] = await Promise.all([p.waitForEvent('download'), p.getByRole('button', { name: 'Word', exact: true }).click()])
await docx.saveAs(`${out}/flow.docx`)
console.log('errors', errors)
await b.close()
